### ISSUE TITLE
Writer

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#10]
Visu pirma JSON faile yra tavo padaryta skiltis
        "WRITER":{
                "FILENAME":"output.vtk"
        },

Kur tu ja naudoji?
Antra gerau FILENAME nurodyti be galunes, nes jei rasysi tarpinius rezultatus tai naudok tokia forma:
PVZ: filename="output"
output_000000000.vtk
output_000001000.vtk
output_000002000.vtk
output_000001000.vtk
ir taip toliau kur skaicius gali nurodyti pvz daleliu kieki.
Tokiu budu nebus konflikto skaitymo rasymo vienu metu, antra galesi per paraview sekti kaip pildo daleles vieno mygtuko paspaudimu.

P.S. kaip ir snekejome situ jau nebereikia
         vector<REAL>intervals;
         int index=duomenys["DISTRIBUTION"]["COUNT"];
         for(int k=0;k<index;k++)
         {
                 intervals.push_back(duomenys["DISTRIBUTION"]["RADIUS"][k]);
         }
     radius_index->SetName("PARTICLE_TYPE");
     radius_index->SetNumberOfComponents(1);
     radius_index->SetNumberOfTuples(data->getNumberOfPoints());

**Comment by rolaxxxx** [comment]
Nereikalingos dalys pasalintos

**Comment by rolaxxxx** [comment]
idejau formata cube_rez_(daleliu kiekis).vtk
