### ISSUE TITLE
Reader

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#11]
Reader klase turi buti skirta VTK failo nuskaitymui kuriame yra is anksto paruostas dalinis pakinimas. Jei vartotojas nenurodo tai failo ir neskaito
Cia kalbu apie JSON dali 
 "INPUT":{
                "TYPE":"STANDART",
                "filename":"input.vtk"
        },
P.S. Tipo cia nereikia, nes VTK failas ir taip viska apraso ir nieko kito nebus.

Visa sita dalis kas yra dabar parasyta turi buti ne cia

void Reader::read(Data * data,std::string filename)
{
   /// nuskaitome pradines daleliu duomenis is failo  
   std::string configData;
         std::ifstream t(filename);
         std::string str((std::istreambuf_iterator<char>(t)),std::istreambuf_iterator<char>());
         configData=str;
         data->setDuomenys(configData);
}

**Comment by rolaxxxx** [comment]
Reader parasytas
