### ISSUE TITLE
Cylinder packing

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#14]
Pakuoja blogai. taip pat poringumas blogas. Cia tik pakeitus tavo pateiktame JSON faile radius i 0.005 kad greiciau pakintu. Paveikslelyje pavaizduotos daleles yra 10 kartu mazesnes kad isryskinti kad negerai.

viso daleliu 82006
poringumas 1.08426

![Cylindras](https://user-images.githubusercontent.com/6221055/64689995-155c5180-d498-11e9-92e8-09cc8ad67074.png)

**Comment by rolaxxxx** [comment]
Cilindro pakavimas sutvarkytas ( dviejuose sonuose siektiek kerta sienas )
