### ISSUE TITLE
JSON pavyzdziai

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#16]
Jei kazko nereikia pvz Paieskoje:
                "BMIN":[0,0,0],
                "BMAX":[0.025,0.005,0.001]

Tai ir ismesk is pavyzdiniu JSON failu, nes neaisku ar reikia ju ar ne

**Comment by rolaxxxx** [comment]
Is kubo katik pasalinau siuos duomenis. Cylindre pervadinsiu boundaries sekcijoje esancius bmin bmax i cylindro apacia ir virsu

**Comment by rolaxxxx** [comment]
Atnaujinti json failai nėra įkelti į githuba

**Comment by rolaxxxx** [comment]
Atnaujinau
