### ISSUE TITLE
Packinimo bugas

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#17]
Kaip supraast kad kaikuriios daleles yra pozicijoje 0,0,0 o radius yra 0?
![Screenshot_20190913_154424](https://user-images.githubusercontent.com/6221055/64863388-66597a80-d63d-11e9-9445-815032370f0d.png)

**Comment by rolaxxxx** [comment]
Is tiesu ta pati pastebejau ir su Cylindru kai bandziau pakuoti. bandau rasti beda random klaseje nes niekas kitas is esmes nebuvo pakeista

**Comment by rolaxxxx** [comment]
Turetu kubas ir cilindras normaliai veikti
