### ISSUE TITLE
Nedarkyk kodo

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#20]
Ir vel pradedi darkyti koda, pvz cia 78 eilute, cia apskritai turi buti JSON faile esancio parametro reiksme, vietoj Cylinder_rez.vtk

77 | vtkDataSetWriter *dsw = vtkDataSetWriter::New(); // reikia pakeisti i smart pointer // ant cylindro luzta
78 | dsw->SetFileName("Cylinder_rez.vtk");
79 | dsw->SetFileTypeToBinary();

**Comment by rolaxxxx** [comment]
Failo reiksme ideta. Smart pointeri pakeisiu siektiek veliau kai galesiu pratestuoti jau veikiancius pakavimus. (ant cilindro smart pointeris luzo)

**Comment by rolaxxxx** [comment]
Smart pointer katik praejus visus tris pakavimus veikia

**Comment by rolaxxxx** [comment]
![ref](https://user-images.githubusercontent.com/31417711/65506160-a0473e00-ded3-11e9-8c68-3a60428c65ac.png)


Cylindras pabaiges pakuotis ant writerio nuluzta. turbut netinkamai naudoju smart pointeri

**Comment by rolaxxxx** [comment]
![image](https://user-images.githubusercontent.com/31417711/65506320-fae09a00-ded3-11e9-8e28-578280bf0621.png)

**Comment by rolaxxxx** [comment]
tiesiog palikau dsw.delete nes kitaip gaunu iskarto segmentation faulta su smart pointeriu
