### ISSUE TITLE
Mesh cube bugas

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#23]
Bandymas supakuoti mesho pagalba paprasta cube, stai kas gavosi.
![bug](https://user-images.githubusercontent.com/6221055/65419088-8f7cc680-de06-11e9-9e61-c26ebe0167f4.png)

[data.zip](https://github.com/rolaxxxx/Packing/files/3641719/data.zip)

**Comment by rolaxxxx** [comment]
![rt](https://user-images.githubusercontent.com/31417711/65503914-9d961a00-dece-11e9-856e-44453d7daf50.png)



Sutvarkyta

**Comment by rolaxxxx** [comment]
![image](https://user-images.githubusercontent.com/31417711/65539706-a6104400-df12-11e9-8043-1a530eaeabb4.png)

**Comment by rolaxxxx** [comment]
![image](https://user-images.githubusercontent.com/31417711/65542491-f5a53e80-df17-11e9-8f4c-5e71a930a504.png)

**Comment by rolaxxxx** [comment]
![image](https://user-images.githubusercontent.com/31417711/65543202-66992600-df19-11e9-9487-e4e036604be8.png)

**Comment by rolaxxxx** [comment]
![sf](https://user-images.githubusercontent.com/31417711/65666313-0b188680-e046-11e9-9c4c-74db5bd39592.png)
 
cilindras lokaliai

**Comment by rolaxxxx** [comment]
![def](https://user-images.githubusercontent.com/31417711/65667370-4451f600-e048-11e9-9378-a0e9ad4c033f.png)


tas pats cylindras ant serverio. Galbut vtk versijos arba gcc versija duoda kazkoki skirtuma ?

**Comment by rolaxxxx** [comment]
![111](https://user-images.githubusercontent.com/31417711/65668062-b2e38380-e049-11e9-8c47-6aa96f84299b.png)
![222](https://user-images.githubusercontent.com/31417711/65668064-b2e38380-e049-11e9-87e9-9dcbac7d39f1.png)
![333](https://user-images.githubusercontent.com/31417711/65668065-b2e38380-e049-11e9-9a97-52d34602f4cf.png)



su Mesh supakuota cilindra idedu i didesne dezute ir pakuoju dezute su Mesh. daryta lokaliai

**Comment by rolaxxxx** [comment]
Ikeliau savo lokalu koda dar karta i githuba ir parasiau kaip reiketu naudotis Mesh.json atnaujintu failu kad pakuotu nuo faile esancios stadijos
