### ISSUE TITLE
Rezultatu irasymas

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#24]
Norėtūsi kad galutinis pakinimo rezultatas būtų įrašytas konkrečiai tokiu pavadinimu kokiu nurodytas config faile nes taip patogiau toliau juos apdoroti. Tarpinius rezultatus galima palikti taip kaip yra dabar arba kazkaip kitaip vadinti. P.S. Realiai Paraview nelabai megsta tokio pavadinimo formos kokia tu uzdejai. Jam patogiau tokia forma:
result_0000000.vtk
result_0000123.vtk
result_0052123.vtk
ir taip toliau, tokiu budu paraview pamato tai kaip serija.
Taip pat jei daromi tarpiniai rezulatatai tuomet juos reiketu istrinti paleidziant programa kad nesimaisytu rezultatai su pries tai buvusiu paleidimu.

**Comment by rolaxxxx** [comment]
Ar FINAL_(daleliu kiekis kas 10000).vtk yra tinkamas formatas paraview ar reikia nuliu isvedime jau nuo pat pradziu :


FINAL_0010000.vtk
FINAL_10000.vtk
