### ISSUE TITLE
Mesh.cpp

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#26]
Cia kaip suprasti? if(ilgis<duomenys["DISTRIBUTION"]["RMAX"]) kur randasi mesh check.
Is principo ka jis cia daro, taigi sfera turi savo spinduli!!!!!! ir beto ta funkcija milijonus kartu kvieciama, tai kodel kiekviena karta reikia parsinti json faila?

**Comment by wincrash** [comment]
Tas pats ir su cylindru, kam jam reikalingas     RMAX_tmp=duomenys["DISTRIBUTION"]["RMAX"];
??????

**Comment by rolaxxxx** [comment]
Istrinta
