### ISSUE TITLE
Turio ir Porocity skaiciavimas

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#30]
Normaliai implementuok geometrijos turio skaiciavima mesh boundaries. kad tinkamai skaiciuotu porocity

**Comment by rolaxxxx** [comment]
O kaip tada gausis su ypac  keistos geometrijos turiu? nes is failo gaunu minimuma vieno krasto ir maximuma i kita puse, tai sito nelabai suprantu

**Comment by rolaxxxx** [comment]
nes jeigu viduryje bus tarpas kaip tada reiketu su turiu daryti? ar tiesiog imti turi is turimu krastiniu?

**Comment by wincrash** [comment]
Nepagalvojau apie tai. Tai kolkas paliekam taip kaip yra.
