### ISSUE TITLE
Random generatoriai

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#31]
Kodel isemei uniform generatoriu?
Kodel ARandom turi siuos kintamuosius 	    std::vector<REAL>probs;
    std::vector<REAL>intervals;   Jiems cia ne vieta.

**Comment by rolaxxxx** [comment]
Mes kai kalbejome sakete jog uniform nebeprireiks ir kad nereiketu dvieju skirtingu distribuciju testuoti tiesiog uniform issemiau bet galiu nesunkiai ideti atgal

**Comment by rolaxxxx** [comment]
std::vectorprobs;
std::vectorintervals Perkelti i Discrete metoda

**Comment by rolaxxxx** [comment]
Uniform idetas
