### ISSUE TITLE
Rezultatu isvedimas

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#33]
Tarpiniai isvedimai (kur iraso i vtk faila) yra gerai. Labai patogu debuginti. Taciau kai dabar pradejau daugiau packinti, pasidaro nepatogu tai kad nezinai koks bus galutinio packinimo failo pavadinimas.
Ar gali padaryti taip kad config faile gali nurodyti ar isvedineti tarpinius rezultatus, jei taip tai irasineja taip kaip dabar, jei ne tai tarpiniu rezultatu nerasys. 
Ir gale kai baigesi pakinimas kad irasytu faila lygiai tokiu pavadinimu kokis irasytas i config faila. Tokiu budu tiksliai zinosiu kur yra galutinis variantas.
Aciu :D

**Comment by rolaxxxx** [comment]
Idejau switcha ijungti arba isjungti tarpinius isvedimus ir taip pat idejau dar ir daleliu kieki kas kiek butu galima isvesti tarpinius rezultatus

**Comment by rolaxxxx** [comment]
![image](https://user-images.githubusercontent.com/31417711/67668239-37daf900-f978-11e9-86e2-735ea9a7e432.png)

**Comment by rolaxxxx** [comment]
Problema iskilo su objekto sukurimu viduje naudojant nhlon json biblioteka. problema sutvarkyta
