### ISSUE TITLE
Algoritmas

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#34]
Ziurek, kiek suprantu as algoritmo puses, turetu buti taip. Tu imi 3 sferas, ir pridedi 4 kuri liecia tas tris.
Bet ziurek ka tavo algoritmas daro. Kaip paaiskinsi?
![image](https://user-images.githubusercontent.com/6221055/67566575-d117ce80-f730-11e9-9fe8-e61fdcf0fe8a.png)

**Comment by rolaxxxx** [comment]
![file1](https://user-images.githubusercontent.com/31417711/68107263-ea690980-feec-11e9-9a93-5ea5467200de.png)

**Comment by rolaxxxx** [comment]
![fil2](https://user-images.githubusercontent.com/31417711/68108944-eb506a00-fef1-11e9-800e-ecf071ba9d06.png)

**Comment by rolaxxxx** [comment]
![fil2ef](https://user-images.githubusercontent.com/31417711/68109000-26529d80-fef2-11e9-9736-7ca628287d25.png)
