### ISSUE TITLE
Mesh porocity skaiciavimas

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#35]
Idek i koda kad normaliai skaiciuotu porocity

Cia kaip is mesho gauti jo turi.

    vtkMassProperties*mass=vtkMassProperties::New();
    mass->SetInputData(readerMesh->GetOutput());
    mass->Update();
    std::cout<<"Volume = "<<mass->GetVolume()<<"\n";

**Comment by rolaxxxx** [comment]
updated
