### ISSUE TITLE
Papildoma opcija

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#38]
Reikia papildomos opcijos:
Dabar pas tave yra taip, imasi naujas R is skirstinio ir ji bando deti, jei nepavyksta ideti sferos, jis suka  toliau "do" cikla kol pavyksta ideti arba baigia darba.
Padaryk taip kad kiekviena karta kai pradeda do cikla jis paima nauja R reiksme.
Padaryk JSON faile "SEARCH" skyriuje sukurk atributa toki ka leisti pasirinkti ar dabartinis algoritmas ar modifikuotas.

**Comment by rolaxxxx** [comment]
idetas pasirinkimas
