### ISSUE TITLE
Klases sablonai

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#4]
Jei darai klases kopija, ir kuria nauja klases su kitu pavadinimu. Tai neuztenka tik klase ir faila pervadinti reikia ir headeri sutvarkyti t.y. preprocesoriu #ifndef RANDOMUNIFORM_H  kad irgi butu unikalus ir nesidubliuotu.
Si klaida yra RandomDiscrete.h faile

**Comment by rolaxxxx** [comment]
Pakeiciau
