### ISSUE TITLE
Klasiu hierarchija

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#5]
Abstrakti klase turi tureti kuo maziau kintamuju ir tureti funkcijas tik tas kurios bendros iskeldintomis klasemes. 
Tavo atveju jei pvz ziurai i Arandom klase yra bardakas. Visi kintamieji ar jie bus naudoti ar ne yra cia. Kodel? 
Pvz     Data* data; kam jis tau apskritai? Dabar paziurejau apskritai ten neturetu buti kintamuju, is nebent json duomenys; 
Taip pat pamastyk metodas getNextValue(); ar tikrai reikia kiekviena karta imti nauja seada, laika ir kurti naujai skirstini, kai tik nori gauti viena random skaiciu? ne paprasciau butu tai iskelti i klases kintamuosius ir poto tik kviesti viena metoda "return unif(re);" 

P.S  static kintamieji yra BLOGIS, jei labai jau reikia reiketu naudoti "Singleton" (apie tai pasiskaityk). Siuo atveju Random klasese static tikrai nereikia!!!!!!!!!!

**Comment by rolaxxxx** [comment]
Static kintamieji pakeisti
