### ISSUE TITLE
Porosity skaiciavimas

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#6]
Visu pirma figuros turi turi iskelti is metodo "void SpherePackingAlgorithm::pack()" i klase ABoundaries kuri turetu abstrakcia funkcija, o jau konkreti boundaries klase ja implementuotu ir tinkamai skaiciuotu turi pagal boundary tipa.

Daleliu turio skaiciavimas turi buti vel ne ""void SpherePackingAlgorithm::pack()", reiketu deti greiciausiai i data klase metoda insertNextPoint(PointType p); ir kad Data klase grazuntu bendra turi.

**Comment by rolaxxxx** [comment]
Kubo ir cilindro boundai ideti i savas klases. Sferu turis skaiciuojamas insertnextPoint klaseje
