### ISSUE TITLE
VTK memory leak

### ISSUE THREAD

**Issue by wincrash** [rolaxxxx/Packing#8]
Jei kuri VTK objekta taip 
          vtkDataSetWriter *dsw = vtkDataSetWriter::New();
Tai gale turi kviesti metoda dsw->Delete() kitaip pas tave memory leakas bus
Jei kuri 
          vtkSmartPointer<vtkDataSetWriter> dsw = vtkSmartPointer<vtkDataSetWriter>::New();
Tuomet nereikia.

**Comment by rolaxxxx** [comment]
sutvarkyta

**Comment by rolaxxxx** [comment]
Pakeitus i smart pointer kas 10000 darant isvedima programa tiesiog nuluzta. Naudojant pointer writeri ir delete taip pat nuluzta. Nenaudojant delete isveda kas 10000.

**Comment by rolaxxxx** [comment]
Smart pointer idetas
